import {
  factorial,
  permutation,
  shuffle as bigintShuffle,
  forEachPerm,
  nChooseK,
  combo,
  allCombos,
  nextBitCombo,
  allBitCombos,
  forEachCombo,
  bitCombo,
  bitComboToR,
  bitLength,
  forEachBitCombo,
  randomBigInt,
  randomPermutation,
  randomCombo,
  randomBitCombo
} from './src/perms.js';

export {
  factorial,
  permutation,
  bigintShuffle,
  forEachPerm,
  nChooseK,
  combo,
  allCombos,
  nextBitCombo,
  allBitCombos,
  forEachCombo,
  bitCombo,
  bitComboToR,
  bitLength,
  forEachBitCombo,
  randomBigInt,
  randomPermutation,
  randomCombo,
  randomBitCombo
};
